project:
  type: website
  output-dir: docs
  render:
    - "**/*.qmd"

website:
  title: "Pavel Logaƒçev"
  site-url: https://plogacev.github.io
  description: "Freelance Data Scientist"
  page-navigation: true
  back-to-top-navigation: true

  navbar:
    tools:
    - icon: github
      href: https://github.com/plogacev
    - icon: linkedin
      href: https://www.linkedin.com/in/pavel-logacev
    right:
      - text: About
        aria-label: "About"
        href: about/index.qmd
      - text: Projects
        aria-label: "Projects"
        href: projects/index.qmd
      - text: Blog
        aria-label: "Blog"
        href: blog/index.qmd
      - text: Contact
        aria-label: "Contact"
        href: contact.qmd

format:
  html:
    theme:
      light:
        - cosmo
        - assets/css/custom.scss
    code-link: true
    pagetitle: "{{< meta title >}}"
    lightbox: true

execute:
  freeze: auto
